version: '2'

services:
  jenkins:
    image: chavomar/jenkins:0.0.6
    ports:
      - "8080:8080"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker